trailingComma: 'all'
tabWidth: 2
singleQuote: true
jsxBracketSameLine: false
jsxSingleQuote: true
arrowParens: always
overrides:
  - files: '*.sol'
    options:
      printWidth: 80
      tabWidth: 4
      useTabs: false
      singleQuote: false
      bracketSpacing: false
